[package]
name = "roze-opentelemetry"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
opentelemetry = "0.31"
opentelemetry-otlp = { version = "0.31", features = ["grpc-tonic", "http-proto", "reqwest-rustls"] }
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio"] }
roze-config = { path = "../roze-config" }
roze-context = { path = "../roze-context" }
