[package]
name = "roze-rate-limit"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
dashmap.workspace = true
roze-redis = { path = "../roze-redis" }
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
