[package]
name = "user-api-service"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
config.workspace = true
poem.workspace = true
prost.workspace = true
roze-core = { path = "../../roze-core" }
serde.workspace = true
sea-orm.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true
tonic-build.workspace = true
