[package]
name = "roze-nats"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
async-nats = { version = "0.50.0", default-features = false, features = [
    "server_2_10",
    "server_2_11",
    "server_2_12",
    "server_2_14",
    "service",
    "ring",
    "jetstream",
    "nkeys",
    "crypto",
    "object-store",
    "kv",
    "nuid",
] }
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
roze-context = { path = "../roze-context" }
roze-eventbus = { path = "../roze-eventbus" }
roze-mq = { path = "../roze-mq" }
roze-trace = { path = "../roze-trace" }

[dev-dependencies]
roze-metrics = { path = "../roze-metrics" }
