[package]
name = "roze-service"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
roze-shutdown = { path = "../roze-shutdown" }
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
roze-metrics = { path = "../roze-metrics" }
