[package]
name = "roze-ws"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
dashmap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "ws_hub"
harness = false
