[package]
name = "roze-jwt"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
jsonwebtoken.workspace = true
reqwest.workspace = true
roze-auth = { path = "../roze-auth" }
roze-config = { path = "../roze-config" }
serde.workspace = true
tokio.workspace = true
