[package]
name = "roze-admin"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
serde.workspace = true
roze-config = { path = "../roze-config" }
roze-mq = { path = "../roze-mq" }
roze-rpc = { path = "../roze-rpc" }

[dev-dependencies]
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
