[package]
name = "roze-dtm-service"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
config.workspace = true
http.workspace = true
roze-dtm = { path = "../../crates/roze-dtm" }
roze-config = { path = "../../crates/roze-config" }
roze-health = { path = "../../crates/roze-health" }
roze-http = { path = "../../crates/roze-http" }
roze-log = { path = "../../crates/roze-log" }
roze-metrics = { path = "../../crates/roze-metrics" }
roze-result = { path = "../../crates/roze-result" }
roze-service = { path = "../../crates/roze-service" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
