[package]
name = "rozectl"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
thiserror.workspace = true
toml_edit.workspace = true
tokio.workspace = true
reqwest.workspace = true
roze-ent = { git = "https://github.com/roze-team/roze-ent.git", rev = "cb54b7dd1f83cf032aa381857c2f6283cab29177" }
roze-middleware = { path = "../../crates/roze-middleware" }
roze-config = { path = "../../crates/roze-config" }
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
regex.workspace = true
config.workspace = true

[dev-dependencies]
tempfile.workspace = true
