[package]
name = "rozectl"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
thiserror.workspace = true
toml_edit.workspace = true
tokio.workspace = true
sqlx.workspace = true
mongodb.workspace = true
futures-util.workspace = true
reqwest.workspace = true
roze-sqlx = { path = "../../crates/roze-sqlx" }
roze-middleware = { path = "../../crates/roze-middleware" }
serde_json.workspace = true
