[package]
name = "roze-bootstrap"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
roze-health = { path = "../roze-health" }
roze-service = { path = "../roze-service" }
roze-shutdown = { path = "../roze-shutdown" }
tokio.workspace = true
