[package]
name = "roze-middleware"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
roze-auth = { path = "../roze-auth" }
roze-config = { path = "../roze-config" }
roze-context = { path = "../roze-context" }
roze-error = { path = "../roze-error" }
roze-http = { path = "../roze-http" }
roze-metrics = { path = "../roze-metrics" }
roze-resilience = { path = "../roze-resilience" }
roze-jwt = { path = "../roze-jwt" }
roze-trace = { path = "../roze-trace" }
redis.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true

