[package]
name = "roze-config"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
reqwest.workspace = true
config.workspace = true
futures-util.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_ignored.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
veil.workspace = true
thiserror.workspace = true
roze-auth = { path = "../roze-auth" }
roze-nats = { path = "../roze-nats" }
roze-rate-limit = { path = "../roze-rate-limit" }
roze-resilience = { path = "../roze-resilience" }
roze-storage = { path = "../roze-storage" }

[dev-dependencies]
roze-metrics = { path = "../roze-metrics" }
