[package]
name = "roze-http"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
matchit.workspace = true
roze-error = { path = "../roze-error" }
roze-result = { path = "../roze-result" }
roze-service = { path = "../roze-service" }
roze-shutdown = { path = "../roze-shutdown" }
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
tokio = { workspace = true, features = ["net"] }
tower.workspace = true
tracing.workspace = true
