[package]
name = "roze-kafka"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = ["memory"]
memory = []
rdkafka = ["dep:rdkafka", "dep:regex"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
roze-mq = { path = "../roze-mq" }
roze-trace = { path = "../roze-trace" }
roze-eventbus = { path = "../roze-eventbus" }

[dependencies.rdkafka]
version = "0.36"
optional = true
default-features = false
features = ["tokio"]

[dependencies.regex]
version = "1"
optional = true
