use std::collections::HashSet;

use crate::{
    generator::{rest, to_snake_case},
    parser::{ApiSpec, Field, FieldSource, HttpMethod, RestRoute, TypeDef},
};

pub fn render_ts_client(spec: &ApiSpec) -> String {
    let mut out =
        String::from("/* eslint-disable */\n// Generated by rozectl. Do not edit by hand.\n\n");
    out.push_str("export interface RequestOptions {\n");
    out.push_str("  baseUrl?: string;\n");
    out.push_str("  headers?: Record<string, string>;\n");
    out.push_str("  fetch?: typeof fetch;\n");
    out.push_str("  authToken?: string | (() => string | Promise<string>);\n");
    out.push_str("  timeoutMs?: number;\n");
    out.push_str("  signal?: AbortSignal;\n");
    out.push_str("  maxAttempts?: number;\n");
    out.push_str("  retryBaseDelayMs?: number;\n");
    out.push_str("  beforeRequest?: (url: string, init: RequestInit) => RequestInit | Promise<RequestInit>;\n");
    out.push_str(
        "  afterResponse?: (response: Response, attempt: number) => void | Promise<void>;\n",
    );
    out.push_str("}\n\n");
    out.push_str("export class RozeApiError extends Error {\n");
    out.push_str("  constructor(public readonly status: number, public readonly code: string, message: string, public readonly traceId?: string, public readonly details?: unknown, public readonly retryAfter?: string) { super(message); this.name = 'RozeApiError'; }\n");
    out.push_str("}\n\n");

    for ty in &spec.types {
        out.push_str(&render_interface(spec, ty));
        out.push('\n');
    }

    out.push_str(
        "async function requestJson<T>(method: string, path: string, query: Record<string, unknown>, body: unknown, headers: Record<string, string>, options: RequestOptions): Promise<T> {\n",
    );
    out.push_str("  const fetchImpl = options.fetch ?? fetch;\n");
    out.push_str("  const baseUrl = (options.baseUrl ?? '').replace(/\\/$/, '');\n");
    out.push_str("  const params = new URLSearchParams();\n");
    out.push_str("  for (const [key, value] of Object.entries(query)) {\n");
    out.push_str(
        "    if (value !== undefined && value !== null) params.append(key, String(value));\n",
    );
    out.push_str("  }\n");
    out.push_str("  const qs = params.toString();\n");
    out.push_str("  const url = `${baseUrl}${path}${qs ? `?${qs}` : ''}`;\n");
    out.push_str("  const requestHeaders: Record<string, string> = { ...(options.headers ?? {}), ...headers };\n");
    out.push_str("  const token = typeof options.authToken === 'function' ? await options.authToken() : options.authToken;\n");
    out.push_str("  if (token && !requestHeaders.authorization && !requestHeaders.Authorization) requestHeaders.authorization = `Bearer ${token}`;\n");
    out.push_str("  let init: RequestInit = { method, headers: requestHeaders };\n");
    out.push_str("  if (body !== undefined) {\n");
    out.push_str("    requestHeaders['content-type'] = requestHeaders['content-type'] ?? 'application/json';\n");
    out.push_str("    init.body = JSON.stringify(body);\n");
    out.push_str("  }\n");
    out.push_str("  const idempotent = method === 'GET' || method === 'HEAD';\n");
    out.push_str("  const maxAttempts = idempotent ? Math.max(1, Math.min(options.maxAttempts ?? 1, 5)) : 1;\n");
    out.push_str("  let response: Response | undefined;\n");
    out.push_str("  for (let attempt = 1; attempt <= maxAttempts; attempt++) {\n");
    out.push_str("    if (options.signal?.aborted) throw options.signal.reason ?? new DOMException('Aborted', 'AbortError');\n");
    out.push_str("    const controller = new AbortController();\n");
    out.push_str("    const abort = () => controller.abort(options.signal?.reason);\n");
    out.push_str("    options.signal?.addEventListener('abort', abort, { once: true });\n");
    out.push_str("    const timer = options.timeoutMs && options.timeoutMs > 0 ? setTimeout(() => controller.abort(new DOMException('Request timed out', 'TimeoutError')), options.timeoutMs) : undefined;\n");
    out.push_str("    const attemptInit = options.beforeRequest ? await options.beforeRequest(url, { ...init, signal: controller.signal }) : { ...init, signal: controller.signal };\n");
    out.push_str("    let attemptResponse: Response;\n");
    out.push_str("    try {\n");
    out.push_str("      attemptResponse = await fetchImpl(url, attemptInit);\n");
    out.push_str("    } catch (error) {\n");
    out.push_str("      if (controller.signal.aborted || attempt === maxAttempts) throw error;\n");
    out.push_str("      await new Promise(resolve => setTimeout(resolve, Math.random() * (options.retryBaseDelayMs ?? 100) * 2 ** (attempt - 1)));\n");
    out.push_str("      continue;\n");
    out.push_str("    } finally {\n");
    out.push_str("      if (timer !== undefined) clearTimeout(timer);\n");
    out.push_str("      options.signal?.removeEventListener('abort', abort);\n");
    out.push_str("    }\n");
    out.push_str("    response = attemptResponse;\n");
    out.push_str("    await options.afterResponse?.(attemptResponse, attempt);\n");
    out.push_str("    if (attemptResponse.ok || ![429, 502, 503, 504].includes(attemptResponse.status) || attempt === maxAttempts) break;\n");
    out.push_str("    await attemptResponse.body?.cancel();\n");
    out.push_str("    const retryAfter = Number(attemptResponse.headers.get('retry-after'));\n");
    out.push_str("    const cap = (options.retryBaseDelayMs ?? 100) * 2 ** (attempt - 1);\n");
    out.push_str("    const delay = Number.isFinite(retryAfter) && retryAfter >= 0 ? retryAfter * 1000 : Math.random() * cap;\n");
    out.push_str("    await new Promise(resolve => setTimeout(resolve, delay));\n");
    out.push_str("  }\n");
    out.push_str("  if (!response) throw new Error('request completed without a response');\n");
    out.push_str("  if (!response.ok) {\n");
    out.push_str("    const text = await response.text();\n");
    out.push_str("    let error: Record<string, unknown> = {};\n");
    out.push_str("    try { error = JSON.parse(text) as Record<string, unknown>; } catch { /* non-JSON upstream response */ }\n");
    out.push_str("    const code = typeof error.code === 'string' || typeof error.code === 'number' ? String(error.code) : `HTTP_${response.status}`;\n");
    out.push_str("    const message = typeof error.message === 'string' ? error.message : (text || `HTTP ${response.status}`);\n");
    out.push_str("    const traceId = typeof error.trace_id === 'string' ? error.trace_id : (response.headers.get('x-trace-id') ?? undefined);\n");
    out.push_str("    throw new RozeApiError(response.status, code, message, traceId, error.details, response.headers.get('retry-after') ?? undefined);\n");
    out.push_str("  }\n");
    out.push_str("  if (response.status === 204) return undefined as T;\n");
    out.push_str("  return await response.json() as T;\n");
    out.push_str("}\n\n");

    for route in &spec.rest_routes {
        if route.websocket {
            continue;
        }
        out.push_str(&render_route_function(spec, route));
        out.push('\n');
    }

    out.push_str(&render_reporting_ts(spec));

    out
}

pub fn render_js_client(spec: &ApiSpec) -> String {
    let mut out =
        String::from("/* eslint-disable */\n// Generated by rozectl. Do not edit by hand.\n\n");
    out.push_str("/**\n");
    out.push_str(" * @typedef {Object} RequestOptions\n");
    out.push_str(" * @property {string} [baseUrl]\n");
    out.push_str(" * @property {Record<string, string>} [headers]\n");
    out.push_str(" * @property {typeof fetch} [fetch]\n");
    out.push_str(" * @property {string|(() => string|Promise<string>)} [authToken]\n");
    out.push_str(" * @property {number} [timeoutMs]\n");
    out.push_str(" * @property {AbortSignal} [signal]\n");
    out.push_str(" * @property {number} [maxAttempts]\n");
    out.push_str(" * @property {number} [retryBaseDelayMs]\n");
    out.push_str(" * @property {(url: string, init: RequestInit) => RequestInit|Promise<RequestInit>} [beforeRequest]\n");
    out.push_str(" * @property {(response: Response, attempt: number) => void|Promise<void>} [afterResponse]\n");
    out.push_str(" */\n\n");
    out.push_str("export class RozeApiError extends Error {\n");
    out.push_str("  constructor(status, code, message, traceId, details, retryAfter) { super(message); this.name = 'RozeApiError'; this.status = status; this.code = code; this.traceId = traceId; this.details = details; this.retryAfter = retryAfter; }\n");
    out.push_str("}\n\n");

    for ty in &spec.types {
        out.push_str(&render_js_typedef(spec, ty));
        out.push('\n');
    }

    out.push_str(
        "async function requestJson(method, path, query, body, headers, options = {}) {\n",
    );
    out.push_str("  const fetchImpl = options.fetch ?? fetch;\n");
    out.push_str("  const baseUrl = (options.baseUrl ?? '').replace(/\\/$/, '');\n");
    out.push_str("  const params = new URLSearchParams();\n");
    out.push_str("  for (const [key, value] of Object.entries(query)) {\n");
    out.push_str(
        "    if (value !== undefined && value !== null) params.append(key, String(value));\n",
    );
    out.push_str("  }\n");
    out.push_str("  const qs = params.toString();\n");
    out.push_str("  const url = `${baseUrl}${path}${qs ? `?${qs}` : ''}`;\n");
    out.push_str("  const requestHeaders = { ...(options.headers ?? {}), ...headers };\n");
    out.push_str("  const token = typeof options.authToken === 'function' ? await options.authToken() : options.authToken;\n");
    out.push_str("  if (token && !requestHeaders.authorization && !requestHeaders.Authorization) requestHeaders.authorization = `Bearer ${token}`;\n");
    out.push_str("  let init = { method, headers: requestHeaders };\n");
    out.push_str("  if (body !== undefined) {\n");
    out.push_str("    requestHeaders['content-type'] = requestHeaders['content-type'] ?? 'application/json';\n");
    out.push_str("    init.body = JSON.stringify(body);\n");
    out.push_str("  }\n");
    out.push_str("  const idempotent = method === 'GET' || method === 'HEAD';\n");
    out.push_str("  const maxAttempts = idempotent ? Math.max(1, Math.min(options.maxAttempts ?? 1, 5)) : 1;\n");
    out.push_str("  let response;\n");
    out.push_str("  for (let attempt = 1; attempt <= maxAttempts; attempt++) {\n");
    out.push_str("    if (options.signal?.aborted) throw options.signal.reason ?? new DOMException('Aborted', 'AbortError');\n");
    out.push_str("    const controller = new AbortController();\n");
    out.push_str("    const abort = () => controller.abort(options.signal?.reason);\n");
    out.push_str("    options.signal?.addEventListener('abort', abort, { once: true });\n");
    out.push_str("    const timer = options.timeoutMs && options.timeoutMs > 0 ? setTimeout(() => controller.abort(new DOMException('Request timed out', 'TimeoutError')), options.timeoutMs) : undefined;\n");
    out.push_str("    const attemptInit = options.beforeRequest ? await options.beforeRequest(url, { ...init, signal: controller.signal }) : { ...init, signal: controller.signal };\n");
    out.push_str("    let attemptResponse;\n");
    out.push_str("    try {\n");
    out.push_str("      attemptResponse = await fetchImpl(url, attemptInit);\n");
    out.push_str("    } catch (error) {\n");
    out.push_str("      if (controller.signal.aborted || attempt === maxAttempts) throw error;\n");
    out.push_str("      await new Promise(resolve => setTimeout(resolve, Math.random() * (options.retryBaseDelayMs ?? 100) * 2 ** (attempt - 1)));\n");
    out.push_str("      continue;\n");
    out.push_str("    } finally {\n");
    out.push_str("      if (timer !== undefined) clearTimeout(timer);\n");
    out.push_str("      options.signal?.removeEventListener('abort', abort);\n");
    out.push_str("    }\n");
    out.push_str("    response = attemptResponse;\n");
    out.push_str("    await options.afterResponse?.(attemptResponse, attempt);\n");
    out.push_str("    if (attemptResponse.ok || ![429, 502, 503, 504].includes(attemptResponse.status) || attempt === maxAttempts) break;\n");
    out.push_str("    await attemptResponse.body?.cancel();\n");
    out.push_str("    const retryAfter = Number(attemptResponse.headers.get('retry-after'));\n");
    out.push_str("    const cap = (options.retryBaseDelayMs ?? 100) * 2 ** (attempt - 1);\n");
    out.push_str("    const delay = Number.isFinite(retryAfter) && retryAfter >= 0 ? retryAfter * 1000 : Math.random() * cap;\n");
    out.push_str("    await new Promise(resolve => setTimeout(resolve, delay));\n");
    out.push_str("  }\n");
    out.push_str("  if (!response) throw new Error('request completed without a response');\n");
    out.push_str("  if (!response.ok) {\n");
    out.push_str("    const text = await response.text();\n");
    out.push_str("    let error = {};\n");
    out.push_str(
        "    try { error = JSON.parse(text); } catch { /* non-JSON upstream response */ }\n",
    );
    out.push_str("    const code = typeof error.code === 'string' || typeof error.code === 'number' ? String(error.code) : `HTTP_${response.status}`;\n");
    out.push_str("    const message = typeof error.message === 'string' ? error.message : (text || `HTTP ${response.status}`);\n");
    out.push_str("    const traceId = typeof error.trace_id === 'string' ? error.trace_id : (response.headers.get('x-trace-id') ?? undefined);\n");
    out.push_str("    throw new RozeApiError(response.status, code, message, traceId, error.details, response.headers.get('retry-after') ?? undefined);\n");
    out.push_str("  }\n");
    out.push_str("  if (response.status === 204) return undefined;\n");
    out.push_str("  return await response.json();\n");
    out.push_str("}\n\n");

    for route in &spec.rest_routes {
        if route.websocket {
            continue;
        }
        out.push_str(&render_js_route_function(spec, route));
        out.push('\n');
    }

    out.push_str(&render_reporting_js(spec));

    out
}

fn render_reporting_ts(spec: &ApiSpec) -> String {
    let exports = rest::full_route_path(spec, "/reports/exports");
    let charts = rest::full_route_path(spec, "/charts/query");
    let mut out = String::from(
        r#"export interface ReportExportRequest {
  report: string;
  format?: 'csv' | 'xlsx';
  columns?: string[];
  filters?: Record<string, unknown>;
  from?: string;
  to?: string;
  timezone?: string;
}

export interface ReportExportResource {
  id: string;
  report: string;
  format: 'csv' | 'xlsx';
  status: 'accepted' | 'running' | 'completed' | 'failed' | 'cancelled' | 'expired';
  progress_percent: number;
  object_key?: string;
  download_url?: string;
  expires_at?: string;
  error?: string;
  tenant_id: string;
}

export interface ChartQueryRequest {
  chart: string;
  dimensions?: string[];
  measures?: string[];
  filters?: Record<string, unknown>;
  group_by?: string[];
  sort?: Array<{ field: string; direction?: 'asc' | 'desc' }>;
  time_bucket?: string;
  from?: string;
  to?: string;
  timezone?: string;
  limit?: number;
}

export interface ChartPoint { timestamp: string; value: number; labels: Record<string, string>; }
export interface ChartSeries { name: string; points: ChartPoint[]; }
export interface ChartQueryResponse {
  chart: string;
  dimensions: string[];
  measures: string[];
  time_bucket?: string;
  timezone?: string;
  scanned_rows: number;
  result_rows: number;
  series: ChartSeries[];
}

"#,
    );
    out.push_str(&format!("export async function createReportExport(request: ReportExportRequest, options: RequestOptions = {{}}): Promise<ReportExportResource> {{ return requestJson('POST', {exports:?}, {{}}, request, {{}}, options); }}\n"));
    out.push_str(&format!("export async function getReportExport(id: string, options: RequestOptions = {{}}): Promise<ReportExportResource> {{ return requestJson('GET', `{exports}/${{encodeURIComponent(id)}}`, {{}}, undefined, {{}}, options); }}\n"));
    out.push_str(&format!("export async function cancelReportExport(id: string, options: RequestOptions = {{}}): Promise<ReportExportResource> {{ return requestJson('DELETE', `{exports}/${{encodeURIComponent(id)}}`, {{}}, undefined, {{}}, options); }}\n"));
    out.push_str(&format!("export async function queryChart(request: ChartQueryRequest, options: RequestOptions = {{}}): Promise<ChartQueryResponse> {{ return requestJson('POST', {charts:?}, {{}}, request, {{}}, options); }}\n"));
    out
}

fn render_reporting_js(spec: &ApiSpec) -> String {
    let exports = rest::full_route_path(spec, "/reports/exports");
    let charts = rest::full_route_path(spec, "/charts/query");
    let mut out = String::from(
        r#"/** @typedef {{ report: string, format?: 'csv'|'xlsx', columns?: string[], filters?: Record<string, unknown>, from?: string, to?: string, timezone?: string }} ReportExportRequest */
/** @typedef {{ id: string, report: string, format: string, status: string, progress_percent: number, object_key?: string, download_url?: string, expires_at?: string, error?: string, tenant_id: string }} ReportExportResource */
/** @typedef {{ chart: string, dimensions?: string[], measures?: string[], filters?: Record<string, unknown>, group_by?: string[], sort?: Array<{field: string, direction?: 'asc'|'desc'}>, time_bucket?: string, from?: string, to?: string, timezone?: string, limit?: number }} ChartQueryRequest */

"#,
    );
    out.push_str(&format!("export async function createReportExport(request, options = {{}}) {{ return requestJson('POST', {exports:?}, {{}}, request, {{}}, options); }}\n"));
    out.push_str(&format!("export async function getReportExport(id, options = {{}}) {{ return requestJson('GET', `{exports}/${{encodeURIComponent(id)}}`, {{}}, undefined, {{}}, options); }}\n"));
    out.push_str(&format!("export async function cancelReportExport(id, options = {{}}) {{ return requestJson('DELETE', `{exports}/${{encodeURIComponent(id)}}`, {{}}, undefined, {{}}, options); }}\n"));
    out.push_str(&format!("export async function queryChart(request, options = {{}}) {{ return requestJson('POST', {charts:?}, {{}}, request, {{}}, options); }}\n"));
    out
}

fn render_interface(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str(&format!("export interface {} {{\n", ty.name));
    for field in fields {
        out.push_str(&format!(
            "  {}: {};\n",
            ts_property(field_property_name(field)),
            ts_type(&field.ty)
        ));
    }
    out.push_str("}\n");
    out
}

fn render_js_typedef(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str("/**\n");
    out.push_str(&format!(" * @typedef {{Object}} {}\n", ty.name));
    for field in fields {
        out.push_str(&format!(
            " * @property {{{}}} {}\n",
            ts_type(&field.ty),
            field_property_name(field)
        ));
    }
    out.push_str(" */\n");
    out
}

fn render_route_function(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_path_template(spec, route, request_ty);
    let query = render_object(spec, request_ty, route, FieldSource::Query);
    let headers = render_object(spec, request_ty, route, FieldSource::Header);
    let body = render_body(spec, request_ty, route);
    let req_param = if expanded_client_fields(spec, request_ty).is_empty() {
        format!("req: {} = {{}}", route.request)
    } else {
        format!("req: {}", route.request)
    };

    let mut out = String::new();
    out.push_str(&format!(
        "export async function {function_name}({req_param}, options: RequestOptions = {{}}): Promise<{response}> {{\n",
        response = route.response,
    ));
    out.push_str(&format!(
        "  return requestJson<{}>({}, {}, {}, {}, {}, options);\n",
        route.response,
        ts_string(http_method(&route.method)),
        path,
        query,
        body,
        headers
    ));
    out.push_str("}\n");
    out
}

fn render_js_route_function(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_path_template(spec, route, request_ty);
    let query = render_object(spec, request_ty, route, FieldSource::Query);
    let headers = render_object(spec, request_ty, route, FieldSource::Header);
    let body = render_body(spec, request_ty, route);
    let req_param = if expanded_client_fields(spec, request_ty).is_empty() {
        "req = {}"
    } else {
        "req"
    };

    let mut out = String::new();
    out.push_str("/**\n");
    if expanded_client_fields(spec, request_ty).is_empty() {
        out.push_str(&format!(" * @param {{{}}} [req]\n", route.request));
    } else {
        out.push_str(&format!(" * @param {{{}}} req\n", route.request));
    }
    out.push_str(" * @param {RequestOptions} [options]\n");
    out.push_str(&format!(" * @returns {{Promise<{}>}}\n", route.response));
    out.push_str(" */\n");
    out.push_str(&format!(
        "export async function {function_name}({req_param}, options = {{}}) {{\n"
    ));
    out.push_str(&format!(
        "  return requestJson({}, {}, {}, {}, {}, options);\n",
        ts_string(http_method(&route.method)),
        path,
        query,
        body,
        headers
    ));
    out.push_str("}\n");
    out
}

fn render_path_template(spec: &ApiSpec, route: &RestRoute, request_ty: &TypeDef) -> String {
    let mut path = rest::full_route_path_for_openapi(spec, route);
    for param in route_path_params(&path) {
        if let Some(field) = expanded_client_fields(spec, request_ty)
            .into_iter()
            .find(|field| normalize_ident(&field_wire_name(field)) == param)
        {
            let access = req_access(field_property_name(field));
            path = path.replace(
                &format!(":{param}"),
                &format!("${{encodeURIComponent(String({access}))}}"),
            );
            path = path.replace(
                &format!("{{{param}}}"),
                &format!("${{encodeURIComponent(String({access}))}}"),
            );
        }
    }
    format!("`{}`", path)
}

fn render_object(
    spec: &ApiSpec,
    request_ty: &TypeDef,
    route: &RestRoute,
    source: FieldSource,
) -> String {
    let mut entries = Vec::new();
    for field in expanded_client_fields(spec, request_ty) {
        if resolve_field_source(field, route) == source {
            entries.push(format!(
                "{}: {}",
                ts_property(field_wire_name(field)),
                req_access(field_property_name(field))
            ));
        }
    }
    if entries.is_empty() {
        "{}".to_string()
    } else {
        format!("{{ {} }}", entries.join(", "))
    }
}

fn render_body(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    if matches!(
        route.method,
        HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
    ) {
        return "undefined".to_string();
    }

    let mut entries = Vec::new();
    for field in expanded_client_fields(spec, request_ty) {
        let source = resolve_field_source(field, route);
        if matches!(source, FieldSource::Json | FieldSource::Form) {
            entries.push(format!(
                "{}: {}",
                ts_property(field_wire_name(field)),
                req_access(field_property_name(field))
            ));
        }
    }
    if entries.is_empty() {
        "undefined".to_string()
    } else {
        format!("{{ {} }}", entries.join(", "))
    }
}

fn resolve_field_source(field: &Field, route: &RestRoute) -> FieldSource {
    match field.source {
        FieldSource::Auto => {
            let name = normalize_ident(&field_wire_name(field));
            if route_path_params(&route.path).contains(&name) {
                FieldSource::Path
            } else if matches!(
                route.method,
                HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
            ) {
                FieldSource::Query
            } else {
                FieldSource::Json
            }
        }
        other => other,
    }
}

fn expanded_client_fields<'a>(spec: &'a ApiSpec, ty: &'a TypeDef) -> Vec<&'a Field> {
    let mut fields = Vec::new();
    let mut stack = HashSet::new();
    expand_client_fields(spec, ty, &mut stack, &mut fields);
    fields
}

fn expand_client_fields<'a>(
    spec: &'a ApiSpec,
    ty: &'a TypeDef,
    stack: &mut HashSet<String>,
    fields: &mut Vec<&'a Field>,
) {
    if !stack.insert(ty.name.clone()) {
        return;
    }
    for field in &ty.fields {
        if field.embedded {
            if let Some(nested) = spec
                .types
                .iter()
                .find(|candidate| candidate.name == field.ty)
            {
                expand_client_fields(spec, nested, stack, fields);
                continue;
            }
        }
        fields.push(field);
    }
    stack.remove(&ty.name);
}

fn route_path_params(path: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut chars = path.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            ':' => {
                let mut name = String::new();
                while let Some(&next) = chars.peek() {
                    if next == '/' {
                        break;
                    }
                    name.push(next);
                    chars.next();
                }
                if !name.is_empty() {
                    names.push(normalize_ident(&name));
                }
            }
            '{' => {
                let mut name = String::new();
                for next in chars.by_ref() {
                    if next == '}' {
                        break;
                    }
                    name.push(next);
                }
                if !name.is_empty() {
                    names.push(normalize_ident(&name));
                }
            }
            _ => {}
        }
    }
    names
}

fn resolved_handler_name(route: &RestRoute) -> String {
    route
        .handler
        .as_ref()
        .map(|handler| to_snake_case(handler))
        .unwrap_or_else(|| rest::handler_name_for_openapi(&route.method, &route.path))
}

fn field_property_name(field: &Field) -> String {
    if matches!(field.source, FieldSource::Header) {
        return field.name.clone();
    }
    field
        .json_name
        .as_deref()
        .or(field.wire_name.as_deref())
        .unwrap_or(&field.name)
        .to_string()
}

fn field_wire_name(field: &Field) -> String {
    field
        .wire_name
        .as_deref()
        .or(field.json_name.as_deref())
        .unwrap_or(&field.name)
        .to_string()
}

fn req_access(property: String) -> String {
    if is_ts_ident(&property) {
        format!("req.{property}")
    } else {
        format!("req[{}]", ts_string(&property))
    }
}

fn ts_property(property: String) -> String {
    if is_ts_ident(&property) {
        property
    } else {
        ts_string(&property)
    }
}

fn ts_type(ty: &str) -> &'static str {
    match ty {
        "String" | "string" => "string",
        "bool" | "boolean" => "boolean",
        "int" | "uint" | "i32" | "i64" | "u32" | "u64" | "int32" | "int64" | "uint32"
        | "uint64" | "float" | "double" | "f32" | "f64" => "number",
        _ => "unknown",
    }
}

fn http_method(method: &HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "GET",
        HttpMethod::Head => "HEAD",
        HttpMethod::Post => "POST",
        HttpMethod::Put => "PUT",
        HttpMethod::Patch => "PATCH",
        HttpMethod::Delete => "DELETE",
    }
}

fn lower_camel(input: &str) -> String {
    let mut parts = input.split('_').filter(|part| !part.is_empty());
    let Some(first) = parts.next() else {
        return "call".to_string();
    };
    let mut out = first.to_string();
    for part in parts {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn normalize_ident(input: &str) -> String {
    input.replace('-', "_")
}

fn is_ts_ident(input: &str) -> bool {
    let mut chars = input.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first == '$' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn ts_string(input: &str) -> String {
    format!("{:?}", input)
}

#[cfg(test)]
mod tests {
    use crate::parser::parse_api;

    use super::*;

    #[test]
    fn renders_typed_fetch_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
                @handler ping
                head /ping (EmptyReq) returns (EmptyResp)
                @handler login
                post /login (LoginReq) returns (LoginResp)
                @handler updateUser
                patch /users/:id (UpdateUserReq) returns (UserResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
                LoginReq {
                    username string `json:"username"`
                    password string `json:"password"`
                }
                UpdateUserReq {
                    id u64 `path:"id"`
                    name string `json:"name"`
                }
                LoginResp {
                    token string `json:"token"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_ts_client(&spec);
        assert!(client.contains("export interface GetUserReq"));
        assert!(client.contains("export async function getUser"));
        assert!(client.contains("`/api/v1/users/${encodeURIComponent(String(req.id))}`"));
        assert!(client.contains("Authorization: req.token"));
        assert!(client.contains("q: req.q"));
        assert!(client.contains("export async function ping"));
        assert!(client.contains("requestJson<EmptyResp>(\"HEAD\""));
        assert!(client.contains("export async function login"));
        assert!(client.contains("username: req.username"));
        assert!(client.contains("export async function updateUser"));
        assert!(client.contains("\"PATCH\""));
        assert!(client.contains("name: req.name"));
        assert!(client.contains("export class RozeApiError extends Error"));
        assert!(client.contains("response.headers.get('x-trace-id')"));
        assert!(client.contains("response.headers.get('retry-after')"));
        assert!(client.contains("authToken?: string | (() => string | Promise<string>)"));
        assert!(client.contains("Math.min(options.maxAttempts ?? 1, 5)"));
        assert!(client.contains("method === 'GET' || method === 'HEAD'"));
        assert!(client.contains("new AbortController()"));
        assert!(client.contains("options.beforeRequest"));
        assert!(client.contains("options.afterResponse"));
        assert!(client.contains("await attemptResponse.body?.cancel()"));
        assert!(client.contains("Math.random() * cap"));
    }

    #[test]
    fn renders_embedded_request_fields_flattened_in_clients() {
        let spec = parse_api(
            r#"
            service user-api {
                @handler createUser
                post /users (CreateUserReq) returns (UserResp)
            }
            type (
                BaseReq {
                    traceId string `json:"traceId"`
                }
                CreateUserReq {
                    BaseReq
                    name string `json:"name"`
                }
                UserResp {
                    id u64 `json:"id"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_ts_client(&spec);

        assert!(client.contains("export interface CreateUserReq"));
        assert!(client.contains("traceId: string;"));
        assert!(client.contains("name: string;"));
        assert!(client.contains("traceId: req.traceId"));
        assert!(client.contains("name: req.name"));
        assert!(!client.contains("baseReq:"));
        assert!(!client.contains("req.baseReq"));
    }

    #[test]
    fn renders_javascript_fetch_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_js_client(&spec);
        assert!(client.contains("@typedef {Object} GetUserReq"));
        assert!(client.contains("export async function getUser(req, options = {})"));
        assert!(client.contains("`/api/v1/users/${encodeURIComponent(String(req.id))}`"));
        assert!(client.contains("Authorization: req.token"));
        assert!(!client.contains(": GetUserReq"));
        assert!(client.contains("throw new RozeApiError"));
        assert!(client.contains("requestHeaders.authorization = `Bearer ${token}`"));
        assert!(client.contains("Math.min(options.maxAttempts ?? 1, 5)"));
    }

    #[test]
    fn renders_client_for_route_without_request() {
        let spec = parse_api(
            r#"
            service health-api {
                @handler health
                get /health returns (HealthResp)
                @handler ping
                get /ping
                @handler logout
                post /logout (LogoutReq)
            }

            type LogoutReq {
                token string `json:"token"`
            }

            type HealthResp {
                ok bool `json:"ok"`
            }
            "#,
        )
        .expect("valid api");

        let client = render_ts_client(&spec);
        assert!(client.contains("export interface EmptyReq"));
        assert!(client.contains("export interface EmptyResp"));
        assert!(client.contains("export async function health(req: EmptyReq = {}"));
        assert!(client.contains("requestJson<HealthResp>(\"GET\", `/health`"));
        assert!(client.contains("export async function ping(req: EmptyReq = {}"));
        assert!(client.contains("requestJson<EmptyResp>(\"GET\", `/ping`"));
        assert!(client.contains("export async function logout(req: LogoutReq"));
        assert!(client.contains("requestJson<EmptyResp>(\"POST\", `/logout`"));

        let js = render_js_client(&spec);
        assert!(js.contains("@param {EmptyReq} [req]"));
        assert!(js.contains("export async function health(req = {}, options = {})"));
    }

    #[test]
    fn renders_async_report_and_bounded_chart_web_clients() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service reports {
                get /health returns (HealthResp)
            }
            type HealthResp {
                ok bool `json:"ok"`
            }
            "#,
        )
        .expect("valid api");

        let ts = render_ts_client(&spec);
        assert!(ts.contains("export interface ReportExportRequest"));
        assert!(ts.contains("export async function createReportExport"));
        assert!(ts.contains("requestJson('POST', \"/api/v1/reports/exports\""));
        assert!(ts.contains("export async function cancelReportExport"));
        assert!(ts.contains("export async function queryChart"));

        let js = render_js_client(&spec);
        assert!(js.contains("@typedef {{ report: string"));
        assert!(js.contains("export async function createReportExport"));
        assert!(js.contains("requestJson('POST', \"/api/v1/charts/query\""));
    }
}
