use std::collections::HashSet;

use crate::{
    generator::{rest, to_snake_case},
    parser::{ApiSpec, Field, FieldSource, HttpMethod, RestRoute, TypeDef},
};

pub fn render_ts_client(spec: &ApiSpec) -> String {
    let mut out =
        String::from("/* eslint-disable */\n// Generated by rozectl. Do not edit by hand.\n\n");
    out.push_str("export interface RequestOptions {\n");
    out.push_str("  baseUrl?: string;\n");
    out.push_str("  headers?: Record<string, string>;\n");
    out.push_str("  fetch?: typeof fetch;\n");
    out.push_str("}\n\n");

    for ty in &spec.types {
        out.push_str(&render_interface(spec, ty));
        out.push('\n');
    }

    out.push_str(
        "async function requestJson<T>(method: string, path: string, query: Record<string, unknown>, body: unknown, headers: Record<string, string>, options: RequestOptions): Promise<T> {\n",
    );
    out.push_str("  const fetchImpl = options.fetch ?? fetch;\n");
    out.push_str("  const baseUrl = (options.baseUrl ?? '').replace(/\\/$/, '');\n");
    out.push_str("  const params = new URLSearchParams();\n");
    out.push_str("  for (const [key, value] of Object.entries(query)) {\n");
    out.push_str(
        "    if (value !== undefined && value !== null) params.append(key, String(value));\n",
    );
    out.push_str("  }\n");
    out.push_str("  const qs = params.toString();\n");
    out.push_str("  const url = `${baseUrl}${path}${qs ? `?${qs}` : ''}`;\n");
    out.push_str("  const requestHeaders: Record<string, string> = { ...(options.headers ?? {}), ...headers };\n");
    out.push_str("  const init: RequestInit = { method, headers: requestHeaders };\n");
    out.push_str("  if (body !== undefined) {\n");
    out.push_str("    requestHeaders['content-type'] = requestHeaders['content-type'] ?? 'application/json';\n");
    out.push_str("    init.body = JSON.stringify(body);\n");
    out.push_str("  }\n");
    out.push_str("  const response = await fetchImpl(url, init);\n");
    out.push_str("  if (!response.ok) throw new Error(`HTTP ${response.status}: ${await response.text()}`);\n");
    out.push_str("  if (response.status === 204) return undefined as T;\n");
    out.push_str("  return await response.json() as T;\n");
    out.push_str("}\n\n");

    for route in &spec.rest_routes {
        out.push_str(&render_route_function(spec, route));
        out.push('\n');
    }

    out
}

pub fn render_js_client(spec: &ApiSpec) -> String {
    let mut out =
        String::from("/* eslint-disable */\n// Generated by rozectl. Do not edit by hand.\n\n");
    out.push_str("/**\n");
    out.push_str(" * @typedef {Object} RequestOptions\n");
    out.push_str(" * @property {string} [baseUrl]\n");
    out.push_str(" * @property {Record<string, string>} [headers]\n");
    out.push_str(" * @property {typeof fetch} [fetch]\n");
    out.push_str(" */\n\n");

    for ty in &spec.types {
        out.push_str(&render_js_typedef(spec, ty));
        out.push('\n');
    }

    out.push_str(
        "async function requestJson(method, path, query, body, headers, options = {}) {\n",
    );
    out.push_str("  const fetchImpl = options.fetch ?? fetch;\n");
    out.push_str("  const baseUrl = (options.baseUrl ?? '').replace(/\\/$/, '');\n");
    out.push_str("  const params = new URLSearchParams();\n");
    out.push_str("  for (const [key, value] of Object.entries(query)) {\n");
    out.push_str(
        "    if (value !== undefined && value !== null) params.append(key, String(value));\n",
    );
    out.push_str("  }\n");
    out.push_str("  const qs = params.toString();\n");
    out.push_str("  const url = `${baseUrl}${path}${qs ? `?${qs}` : ''}`;\n");
    out.push_str("  const requestHeaders = { ...(options.headers ?? {}), ...headers };\n");
    out.push_str("  const init = { method, headers: requestHeaders };\n");
    out.push_str("  if (body !== undefined) {\n");
    out.push_str("    requestHeaders['content-type'] = requestHeaders['content-type'] ?? 'application/json';\n");
    out.push_str("    init.body = JSON.stringify(body);\n");
    out.push_str("  }\n");
    out.push_str("  const response = await fetchImpl(url, init);\n");
    out.push_str("  if (!response.ok) throw new Error(`HTTP ${response.status}: ${await response.text()}`);\n");
    out.push_str("  if (response.status === 204) return undefined;\n");
    out.push_str("  return await response.json();\n");
    out.push_str("}\n\n");

    for route in &spec.rest_routes {
        out.push_str(&render_js_route_function(spec, route));
        out.push('\n');
    }

    out
}

pub fn render_dart_client(spec: &ApiSpec) -> String {
    let mut out = String::from(
        "// Generated by rozectl. Do not edit by hand.\n\nimport 'dart:convert';\n\nimport 'package:http/http.dart' as http;\n\n",
    );

    for ty in &spec.types {
        out.push_str(&render_dart_model(spec, ty));
        out.push('\n');
    }

    out.push_str("class RozeApiClient {\n");
    out.push_str("  RozeApiClient({required this.baseUrl, http.Client? httpClient, Map<String, String>? headers})\n");
    out.push_str("      : _httpClient = httpClient ?? http.Client(),\n");
    out.push_str("        _headers = headers ?? const {};\n\n");
    out.push_str("  final String baseUrl;\n");
    out.push_str("  final http.Client _httpClient;\n");
    out.push_str("  final Map<String, String> _headers;\n\n");

    for route in &spec.rest_routes {
        out.push_str(&render_dart_route_method(spec, route));
        out.push('\n');
    }

    out.push_str("  Uri _uri(String path, [Map<String, Object?> query = const {}]) {\n");
    out.push_str("    final base = Uri.parse(baseUrl.replaceFirst(RegExp(r'/$'), ''));\n");
    out.push_str("    final queryParameters = <String, String>{};\n");
    out.push_str("    for (final entry in query.entries) {\n");
    out.push_str("      final value = entry.value;\n");
    out.push_str("      if (value != null) queryParameters[entry.key] = value.toString();\n");
    out.push_str("    }\n");
    out.push_str("    return Uri.parse('${base.toString()}$path').replace(queryParameters: queryParameters.isEmpty ? null : queryParameters);\n");
    out.push_str("  }\n\n");
    out.push_str("  Future<Map<String, dynamic>> _send(String method, Uri uri, {Map<String, String> headers = const {}, Object? body}) async {\n");
    out.push_str("    final requestHeaders = <String, String>{..._headers, ...headers};\n");
    out.push_str("    http.Response response;\n");
    out.push_str("    switch (method) {\n");
    out.push_str("      case 'GET':\n");
    out.push_str("        response = await _httpClient.get(uri, headers: requestHeaders);\n");
    out.push_str("        break;\n");
    out.push_str("      case 'HEAD':\n");
    out.push_str("        response = await _httpClient.head(uri, headers: requestHeaders);\n");
    out.push_str("        break;\n");
    out.push_str("      case 'DELETE':\n");
    out.push_str("        response = await _httpClient.delete(uri, headers: requestHeaders);\n");
    out.push_str("        break;\n");
    out.push_str("      case 'POST':\n");
    out.push_str("        requestHeaders.putIfAbsent('content-type', () => 'application/json');\n");
    out.push_str("        response = await _httpClient.post(uri, headers: requestHeaders, body: jsonEncode(body));\n");
    out.push_str("        break;\n");
    out.push_str("      case 'PUT':\n");
    out.push_str("        requestHeaders.putIfAbsent('content-type', () => 'application/json');\n");
    out.push_str("        response = await _httpClient.put(uri, headers: requestHeaders, body: jsonEncode(body));\n");
    out.push_str("        break;\n");
    out.push_str("      case 'PATCH':\n");
    out.push_str("        requestHeaders.putIfAbsent('content-type', () => 'application/json');\n");
    out.push_str("        response = await _httpClient.patch(uri, headers: requestHeaders, body: jsonEncode(body));\n");
    out.push_str("        break;\n");
    out.push_str("      default:\n");
    out.push_str("        throw ArgumentError('unsupported method: $method');\n");
    out.push_str("    }\n");
    out.push_str("    if (response.statusCode < 200 || response.statusCode >= 300) {\n");
    out.push_str(
        "      throw http.ClientException('HTTP ${response.statusCode}: ${response.body}', uri);\n",
    );
    out.push_str("    }\n");
    out.push_str("    if (response.body.isEmpty) return <String, dynamic>{};\n");
    out.push_str("    final decoded = jsonDecode(response.body);\n");
    out.push_str("    if (decoded is Map<String, dynamic>) return decoded;\n");
    out.push_str("    throw http.ClientException('expected JSON object response', uri);\n");
    out.push_str("  }\n");
    out.push_str("}\n");

    out
}

pub fn render_java_client(spec: &ApiSpec) -> String {
    let mut out = String::from(
        "// Generated by rozectl. Do not edit by hand.\n\nimport java.io.IOException;\nimport java.net.URI;\nimport java.net.URLEncoder;\nimport java.net.http.HttpClient;\nimport java.net.http.HttpRequest;\nimport java.net.http.HttpResponse;\nimport java.nio.charset.StandardCharsets;\nimport java.util.LinkedHashMap;\nimport java.util.Map;\nimport java.util.StringJoiner;\n\npublic final class RozeApiClient {\n",
    );
    out.push_str("  private final String baseUrl;\n");
    out.push_str("  private final HttpClient httpClient;\n");
    out.push_str("  private final Map<String, String> headers;\n\n");
    out.push_str("  public RozeApiClient(String baseUrl) {\n");
    out.push_str("    this(baseUrl, HttpClient.newHttpClient(), Map.of());\n");
    out.push_str("  }\n\n");
    out.push_str("  public RozeApiClient(String baseUrl, HttpClient httpClient, Map<String, String> headers) {\n");
    out.push_str("    this.baseUrl = trimTrailingSlash(baseUrl);\n");
    out.push_str("    this.httpClient = httpClient;\n");
    out.push_str("    this.headers = headers;\n");
    out.push_str("  }\n\n");

    for route in &spec.rest_routes {
        out.push_str(&render_java_route_method(spec, route));
        out.push('\n');
    }

    for ty in &spec.types {
        out.push_str(&render_java_model(spec, ty));
        out.push('\n');
    }

    out.push_str(
        r#"  private String send(String method, String path, Map<String, Object> query, Map<String, String> headers, String body) throws IOException, InterruptedException {
    String url = baseUrl + path + renderQuery(query);
    HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(url));
    for (Map.Entry<String, String> entry : this.headers.entrySet()) {
      builder.header(entry.getKey(), entry.getValue());
    }
    for (Map.Entry<String, String> entry : headers.entrySet()) {
      builder.header(entry.getKey(), entry.getValue());
    }
    if (body == null) {
      builder.method(method, HttpRequest.BodyPublishers.noBody());
    } else {
      builder.header("content-type", "application/json");
      builder.method(method, HttpRequest.BodyPublishers.ofString(body));
    }
    HttpResponse<String> response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("HTTP " + response.statusCode() + ": " + response.body());
    }
    return response.body();
  }

  private static String renderQuery(Map<String, Object> query) {
    if (query.isEmpty()) return "";
    StringJoiner joiner = new StringJoiner("&", "?", "");
    for (Map.Entry<String, Object> entry : query.entrySet()) {
      Object value = entry.getValue();
      if (value != null) {
        joiner.add(urlEncode(entry.getKey()) + "=" + urlEncode(String.valueOf(value)));
      }
    }
    String rendered = joiner.toString();
    return rendered.equals("?") ? "" : rendered;
  }

  private static String trimTrailingSlash(String value) {
    return value.endsWith("/") ? value.substring(0, value.length() - 1) : value;
  }

  private static String urlEncode(String value) {
    return URLEncoder.encode(value, StandardCharsets.UTF_8);
  }

  private static Map<String, Object> mapOf(Object... values) {
    Map<String, Object> out = new LinkedHashMap<>();
    for (int i = 0; i < values.length; i += 2) {
      out.put(String.valueOf(values[i]), values[i + 1]);
    }
    return out;
  }

  private static Map<String, String> stringMapOf(Object... values) {
    Map<String, String> out = new LinkedHashMap<>();
    for (int i = 0; i < values.length; i += 2) {
      out.put(String.valueOf(values[i]), String.valueOf(values[i + 1]));
    }
    return out;
  }

  private static String jsonObject(Object... values) {
    if (values.length == 0) return "{}";
    StringJoiner joiner = new StringJoiner(",", "{", "}");
    for (int i = 0; i < values.length; i += 2) {
      Object value = values[i + 1];
      if (value != null) {
        joiner.add(jsonString(String.valueOf(values[i])) + ":" + jsonValue(value));
      }
    }
    return joiner.toString();
  }

  private static String jsonValue(Object value) {
    if (value instanceof Number || value instanceof Boolean) return String.valueOf(value);
    return jsonString(String.valueOf(value));
  }

  private static String jsonString(String value) {
    return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
  }
}
"#,
    );

    out
}

pub fn render_kotlin_client(spec: &ApiSpec) -> String {
    let mut out = String::from(
        "// Generated by rozectl. Do not edit by hand.\n\nimport java.io.IOException\nimport java.net.URI\nimport java.net.URLEncoder\nimport java.net.http.HttpClient\nimport java.net.http.HttpRequest\nimport java.net.http.HttpResponse\nimport java.nio.charset.StandardCharsets\n\n",
    );

    for ty in &spec.types {
        out.push_str(&render_kotlin_model(spec, ty));
        out.push('\n');
    }

    out.push_str("class RozeApiClient(\n");
    out.push_str("    baseUrl: String,\n");
    out.push_str("    private val httpClient: HttpClient = HttpClient.newHttpClient(),\n");
    out.push_str("    private val headers: Map<String, String> = emptyMap(),\n");
    out.push_str(") {\n");
    out.push_str("    private val baseUrl: String = baseUrl.trimEnd('/')\n\n");

    for route in &spec.rest_routes {
        out.push_str(&render_kotlin_route_method(spec, route));
        out.push('\n');
    }

    out.push_str(
        r#"    private fun send(method: String, path: String, query: Map<String, Any?>, headers: Map<String, String>, body: String?): String {
        val url = baseUrl + path + renderQuery(query)
        val builder = HttpRequest.newBuilder(URI.create(url))
        this.headers.forEach { (key, value) -> builder.header(key, value) }
        headers.forEach { (key, value) -> builder.header(key, value) }
        if (body == null) {
            builder.method(method, HttpRequest.BodyPublishers.noBody())
        } else {
            builder.header("content-type", "application/json")
            builder.method(method, HttpRequest.BodyPublishers.ofString(body))
        }
        val response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString())
        if (response.statusCode() !in 200..299) {
            throw IOException("HTTP ${response.statusCode()}: ${response.body()}")
        }
        return response.body()
    }

    private fun renderQuery(query: Map<String, Any?>): String {
        val rendered = query
            .filterValues { it != null }
            .map { (key, value) -> "${urlEncode(key)}=${urlEncode(value.toString())}" }
            .joinToString("&")
        return if (rendered.isEmpty()) "" else "?$rendered"
    }

    private fun urlEncode(value: String): String = URLEncoder.encode(value, StandardCharsets.UTF_8)

    private fun jsonObject(vararg values: Pair<String, Any?>): String =
        values.filter { it.second != null }
            .joinToString(prefix = "{", postfix = "}") { (key, value) -> "${jsonString(key)}:${jsonValue(value!!)}" }

    private fun jsonValue(value: Any): String =
        when (value) {
            is Number, is Boolean -> value.toString()
            else -> jsonString(value.toString())
        }

    private fun jsonString(value: String): String =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
"#,
    );

    out
}

pub fn render_swift_client(spec: &ApiSpec) -> String {
    let mut out =
        String::from("// Generated by rozectl. Do not edit by hand.\n\nimport Foundation\n\n");

    for ty in &spec.types {
        out.push_str(&render_swift_model(spec, ty));
        out.push('\n');
    }

    out.push_str("public final class RozeApiClient {\n");
    out.push_str("    private let baseUrl: String\n");
    out.push_str("    private let session: URLSession\n");
    out.push_str("    private let headers: [String: String]\n\n");
    out.push_str("    public init(baseUrl: String, session: URLSession = .shared, headers: [String: String] = [:]) {\n");
    out.push_str(
        "        self.baseUrl = baseUrl.hasSuffix(\"/\") ? String(baseUrl.dropLast()) : baseUrl\n",
    );
    out.push_str("        self.session = session\n");
    out.push_str("        self.headers = headers\n");
    out.push_str("    }\n\n");

    for route in &spec.rest_routes {
        out.push_str(&render_swift_route_method(spec, route));
        out.push('\n');
    }

    out.push_str(
        r#"    private func send(method: String, path: String, query: [String: Any?], headers: [String: String], body: [String: Any?]?) async throws -> String {
        var components = URLComponents(string: baseUrl + path)!
        let queryItems = query.compactMap { key, value -> URLQueryItem? in
            guard let value else { return nil }
            return URLQueryItem(name: key, value: String(describing: value))
        }
        if !queryItems.isEmpty {
            components.queryItems = queryItems
        }
        var request = URLRequest(url: components.url!)
        request.httpMethod = method
        for (key, value) in self.headers {
            request.setValue(value, forHTTPHeaderField: key)
        }
        for (key, value) in headers {
            request.setValue(value, forHTTPHeaderField: key)
        }
        if let body {
            request.setValue("application/json", forHTTPHeaderField: "content-type")
            request.httpBody = try JSONSerialization.data(withJSONObject: body.compactMapValues { $0 })
        }
        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {
            let status = (response as? HTTPURLResponse)?.statusCode ?? -1
            let text = String(data: data, encoding: .utf8) ?? ""
            throw RozeApiError.http(status: status, body: text)
        }
        return String(data: data, encoding: .utf8) ?? ""
    }
}

public enum RozeApiError: Error {
    case http(status: Int, body: String)
}
"#,
    );

    out
}

fn render_java_route_method(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_java_path_expr(spec, route, request_ty);
    let query = render_java_map(spec, request_ty, route, FieldSource::Query);
    let headers = render_java_headers(spec, request_ty, route);
    let body = render_java_body(spec, request_ty, route);

    let mut out = String::new();
    out.push_str(&format!(
        "  public String {function_name}({} req) throws IOException, InterruptedException {{\n",
        route.request
    ));
    out.push_str(&format!(
        "    return send({}, {path}, {query}, {headers}, {body});\n",
        java_string(http_method(&route.method))
    ));
    out.push_str("  }\n");
    out
}

fn render_kotlin_route_method(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_kotlin_path_expr(spec, route, request_ty);
    let query = render_kotlin_map(spec, request_ty, route, FieldSource::Query);
    let headers = render_kotlin_headers(spec, request_ty, route);
    let body = render_kotlin_body(spec, request_ty, route);

    let mut out = String::new();
    out.push_str(&format!(
        "    fun {function_name}(req: {}): String =\n",
        route.request
    ));
    out.push_str(&format!(
        "        send({}, {path}, {query}, {headers}, {body})\n",
        kotlin_string(http_method(&route.method))
    ));
    out
}

fn render_java_model(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str(&format!("  public static final class {} {{\n", ty.name));
    for field in &fields {
        out.push_str(&format!(
            "    public {} {};\n",
            java_type(&field.ty),
            java_field_name(field)
        ));
    }
    out.push('\n');
    out.push_str(&format!("    public {}() {{}}\n\n", ty.name));
    out.push_str(&format!("    public {}(", ty.name));
    let params = fields
        .iter()
        .map(|field| format!("{} {}", java_type(&field.ty), java_field_name(field)))
        .collect::<Vec<_>>();
    out.push_str(&params.join(", "));
    out.push_str(") {\n");
    for field in &fields {
        let name = java_field_name(field);
        out.push_str(&format!("      this.{name} = {name};\n"));
    }
    out.push_str("    }\n");
    out.push_str("  }\n");
    out
}

fn render_kotlin_model(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str(&format!("data class {}(\n", ty.name));
    for field in fields {
        out.push_str(&format!(
            "    val {}: {},\n",
            kotlin_field_name(field),
            kotlin_type(&field.ty)
        ));
    }
    out.push_str(")\n");
    out
}

fn render_swift_route_method(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_swift_path_expr(spec, route, request_ty);
    let query = render_swift_dict(spec, request_ty, route, FieldSource::Query);
    let headers = render_swift_headers(spec, request_ty, route);
    let body = render_swift_body(spec, request_ty, route);

    let mut out = String::new();
    out.push_str(&format!(
        "    public func {function_name}(_ req: {}) async throws -> String {{\n",
        route.request
    ));
    out.push_str(&format!(
        "        try await send(method: {}, path: {path}, query: {query}, headers: {headers}, body: {body})\n",
        swift_string(http_method(&route.method))
    ));
    out.push_str("    }\n");
    out
}

fn render_swift_model(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str(&format!("public struct {}: Codable {{\n", ty.name));
    for field in &fields {
        out.push_str(&format!(
            "    public var {}: {}\n",
            swift_field_name(field),
            swift_type(&field.ty)
        ));
    }
    out.push('\n');
    out.push_str("    public init(");
    let params = fields
        .iter()
        .map(|field| format!("{}: {}", swift_field_name(field), swift_type(&field.ty)))
        .collect::<Vec<_>>();
    out.push_str(&params.join(", "));
    out.push_str(") {\n");
    for field in &fields {
        let name = swift_field_name(field);
        out.push_str(&format!("        self.{name} = {name}\n"));
    }
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn render_interface(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str(&format!("export interface {} {{\n", ty.name));
    for field in fields {
        out.push_str(&format!(
            "  {}: {};\n",
            ts_property(field_property_name(field)),
            ts_type(&field.ty)
        ));
    }
    out.push_str("}\n");
    out
}

fn render_js_typedef(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str("/**\n");
    out.push_str(&format!(" * @typedef {{Object}} {}\n", ty.name));
    for field in fields {
        out.push_str(&format!(
            " * @property {{{}}} {}\n",
            ts_type(&field.ty),
            field_property_name(field)
        ));
    }
    out.push_str(" */\n");
    out
}

fn render_dart_model(spec: &ApiSpec, ty: &TypeDef) -> String {
    let fields = expanded_client_fields(spec, ty);
    let mut out = String::new();
    out.push_str(&format!("class {} {{\n", ty.name));
    out.push_str(&format!("  const {}({{\n", ty.name));
    for field in &fields {
        out.push_str(&format!("    required this.{},\n", dart_field_name(field)));
    }
    out.push_str("  });\n\n");
    for field in &fields {
        out.push_str(&format!(
            "  final {} {};\n",
            dart_type(&field.ty),
            dart_field_name(field)
        ));
    }
    out.push('\n');
    out.push_str(&format!(
        "  factory {}.fromJson(Map<String, dynamic> json) => {}(\n",
        ty.name, ty.name
    ));
    for field in &fields {
        out.push_str(&format!(
            "        {}: {},\n",
            dart_field_name(field),
            dart_from_json_expr(field)
        ));
    }
    out.push_str("      );\n\n");
    out.push_str("  Map<String, dynamic> toJson() => <String, dynamic>{\n");
    for field in &fields {
        out.push_str(&format!(
            "        {}: {},\n",
            dart_string(&field_wire_name(field)),
            dart_field_name(field)
        ));
    }
    out.push_str("      };\n");
    out.push_str("}\n");
    out
}

fn render_route_function(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_path_template(spec, route, request_ty);
    let query = render_object(spec, request_ty, route, FieldSource::Query);
    let headers = render_object(spec, request_ty, route, FieldSource::Header);
    let body = render_body(spec, request_ty, route);
    let req_param = if expanded_client_fields(spec, request_ty).is_empty() {
        format!("req: {} = {{}}", route.request)
    } else {
        format!("req: {}", route.request)
    };

    let mut out = String::new();
    out.push_str(&format!(
        "export async function {function_name}({req_param}, options: RequestOptions = {{}}): Promise<{response}> {{\n",
        response = route.response,
    ));
    out.push_str(&format!(
        "  return requestJson<{}>({}, {}, {}, {}, {}, options);\n",
        route.response,
        ts_string(http_method(&route.method)),
        path,
        query,
        body,
        headers
    ));
    out.push_str("}\n");
    out
}

fn render_js_route_function(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_path_template(spec, route, request_ty);
    let query = render_object(spec, request_ty, route, FieldSource::Query);
    let headers = render_object(spec, request_ty, route, FieldSource::Header);
    let body = render_body(spec, request_ty, route);
    let req_param = if expanded_client_fields(spec, request_ty).is_empty() {
        "req = {}"
    } else {
        "req"
    };

    let mut out = String::new();
    out.push_str("/**\n");
    if expanded_client_fields(spec, request_ty).is_empty() {
        out.push_str(&format!(" * @param {{{}}} [req]\n", route.request));
    } else {
        out.push_str(&format!(" * @param {{{}}} req\n", route.request));
    }
    out.push_str(" * @param {RequestOptions} [options]\n");
    out.push_str(&format!(" * @returns {{Promise<{}>}}\n", route.response));
    out.push_str(" */\n");
    out.push_str(&format!(
        "export async function {function_name}({req_param}, options = {{}}) {{\n"
    ));
    out.push_str(&format!(
        "  return requestJson({}, {}, {}, {}, {}, options);\n",
        ts_string(http_method(&route.method)),
        path,
        query,
        body,
        headers
    ));
    out.push_str("}\n");
    out
}

fn render_dart_route_method(spec: &ApiSpec, route: &RestRoute) -> String {
    let request_ty = spec
        .types
        .iter()
        .find(|ty| ty.name == route.request)
        .expect("route request type should exist before client generation");
    let function_name = lower_camel(&resolved_handler_name(route));
    let path = render_dart_path_template(spec, route, request_ty);
    let query = render_dart_object(spec, request_ty, route, FieldSource::Query);
    let headers = render_dart_headers(spec, request_ty, route);
    let body = render_dart_body(spec, request_ty, route);

    let mut out = String::new();
    out.push_str(&format!(
        "  Future<{}> {}({} req, {{Map<String, String> headers = const {{}}}}) async {{\n",
        route.response, function_name, route.request
    ));
    out.push_str(&format!("    final uri = _uri({}, {});\n", path, query));
    out.push_str(&format!(
        "    final json = await _send({}, uri, headers: <String, String>{{...{}, ...headers}}, body: {});\n",
        dart_string(http_method(&route.method)),
        headers,
        body
    ));
    out.push_str(&format!("    return {}.fromJson(json);\n", route.response));
    out.push_str("  }\n");
    out
}

fn render_path_template(spec: &ApiSpec, route: &RestRoute, request_ty: &TypeDef) -> String {
    let mut path = rest::full_route_path_for_openapi(spec, route);
    for param in route_path_params(&path) {
        if let Some(field) = expanded_client_fields(spec, request_ty)
            .into_iter()
            .find(|field| normalize_ident(&field_wire_name(field)) == param)
        {
            let access = req_access(field_property_name(field));
            path = path.replace(
                &format!(":{param}"),
                &format!("${{encodeURIComponent(String({access}))}}"),
            );
            path = path.replace(
                &format!("{{{param}}}"),
                &format!("${{encodeURIComponent(String({access}))}}"),
            );
        }
    }
    format!("`{}`", path)
}

fn render_dart_path_template(spec: &ApiSpec, route: &RestRoute, request_ty: &TypeDef) -> String {
    let mut path = rest::full_route_path_for_openapi(spec, route);
    for param in route_path_params(&path) {
        if let Some(field) = expanded_client_fields(spec, request_ty)
            .into_iter()
            .find(|field| normalize_ident(&field_wire_name(field)) == param)
        {
            let access = format!("req.{}", dart_field_name(field));
            path = path.replace(
                &format!(":{param}"),
                &format!("${{Uri.encodeComponent({access}.toString())}}"),
            );
            path = path.replace(
                &format!("{{{param}}}"),
                &format!("${{Uri.encodeComponent({access}.toString())}}"),
            );
        }
    }
    format!("'{}'", path)
}

fn render_java_path_expr(spec: &ApiSpec, route: &RestRoute, request_ty: &TypeDef) -> String {
    render_jvm_path_expr(
        spec,
        route,
        request_ty,
        "urlEncode(String.valueOf(req.",
        "))",
    )
}

fn render_kotlin_path_expr(spec: &ApiSpec, route: &RestRoute, request_ty: &TypeDef) -> String {
    render_jvm_path_expr(spec, route, request_ty, "urlEncode(req.", ".toString())")
}

fn render_swift_path_expr(spec: &ApiSpec, route: &RestRoute, request_ty: &TypeDef) -> String {
    let path = rest::full_route_path_for_openapi(spec, route);
    let mut parts = Vec::new();
    let mut cursor = 0;
    let mut literal_start = 0;
    while cursor < path.len() {
        let marker = path.as_bytes()[cursor] as char;
        if marker == ':' || marker == '{' {
            let start = cursor;
            let (end, raw_name) = if marker == ':' {
                cursor += 1;
                let name_start = cursor;
                while cursor < path.len() && path.as_bytes()[cursor] != b'/' {
                    cursor += 1;
                }
                (cursor, &path[name_start..cursor])
            } else {
                cursor += 1;
                let name_start = cursor;
                while cursor < path.len() && path.as_bytes()[cursor] != b'}' {
                    cursor += 1;
                }
                let name_end = cursor;
                if cursor < path.len() {
                    cursor += 1;
                }
                (cursor, &path[name_start..name_end])
            };
            if let Some(field) = expanded_client_fields(spec, request_ty)
                .into_iter()
                .find(|field| normalize_ident(&field_wire_name(field)) == normalize_ident(raw_name))
            {
                if start > literal_start {
                    parts.push(("literal", path[literal_start..start].to_string()));
                }
                parts.push((
                    "expr",
                    format!(
                        "String(describing: req.{}).addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? \"\"",
                        swift_field_name(field)
                    ),
                ));
                literal_start = end;
            }
        } else {
            cursor += 1;
        }
    }
    if literal_start < path.len() {
        parts.push(("literal", path[literal_start..].to_string()));
    }
    if parts.is_empty() {
        return swift_string(&path);
    }
    parts
        .into_iter()
        .filter(|(_, value)| !value.is_empty())
        .map(|(kind, value)| {
            if kind == "literal" {
                swift_string(&value)
            } else {
                value
            }
        })
        .collect::<Vec<_>>()
        .join(" + ")
}

fn render_jvm_path_expr(
    spec: &ApiSpec,
    route: &RestRoute,
    request_ty: &TypeDef,
    prefix: &str,
    suffix: &str,
) -> String {
    let path = rest::full_route_path_for_openapi(spec, route);
    let mut parts = Vec::new();
    let mut cursor = 0;
    let mut literal_start = 0;
    while cursor < path.len() {
        let marker = path.as_bytes()[cursor] as char;
        if marker == ':' || marker == '{' {
            let start = cursor;
            let (end, raw_name) = if marker == ':' {
                cursor += 1;
                let name_start = cursor;
                while cursor < path.len() && path.as_bytes()[cursor] != b'/' {
                    cursor += 1;
                }
                (cursor, &path[name_start..cursor])
            } else {
                cursor += 1;
                let name_start = cursor;
                while cursor < path.len() && path.as_bytes()[cursor] != b'}' {
                    cursor += 1;
                }
                let name_end = cursor;
                if cursor < path.len() {
                    cursor += 1;
                }
                (cursor, &path[name_start..name_end])
            };
            if let Some(field) = expanded_client_fields(spec, request_ty)
                .into_iter()
                .find(|field| normalize_ident(&field_wire_name(field)) == normalize_ident(raw_name))
            {
                if start > literal_start {
                    parts.push(("literal", path[literal_start..start].to_string()));
                }
                let field_name = if prefix.contains("String.valueOf") {
                    java_field_name(field)
                } else {
                    kotlin_field_name(field)
                };
                parts.push(("expr", format!("{prefix}{field_name}{suffix}")));
                literal_start = end;
            }
        } else {
            cursor += 1;
        }
    }
    if literal_start < path.len() {
        parts.push(("literal", path[literal_start..].to_string()));
    }
    if parts.is_empty() {
        return java_string(&path);
    }
    join_jvm_path_parts(parts)
}

fn join_jvm_path_parts(parts: Vec<(&'static str, String)>) -> String {
    parts
        .into_iter()
        .filter(|(_, value)| !value.is_empty())
        .map(|(kind, value)| {
            if kind == "literal" {
                java_string(&value)
            } else {
                value
            }
        })
        .collect::<Vec<_>>()
        .join(" + ")
}

fn render_object(
    spec: &ApiSpec,
    request_ty: &TypeDef,
    route: &RestRoute,
    source: FieldSource,
) -> String {
    let mut entries = Vec::new();
    for field in expanded_client_fields(spec, request_ty) {
        if resolve_field_source(field, route) == source {
            entries.push(format!(
                "{}: {}",
                ts_property(field_wire_name(field)),
                req_access(field_property_name(field))
            ));
        }
    }
    if entries.is_empty() {
        "{}".to_string()
    } else {
        format!("{{ {} }}", entries.join(", "))
    }
}

fn render_dart_object(
    spec: &ApiSpec,
    request_ty: &TypeDef,
    route: &RestRoute,
    source: FieldSource,
) -> String {
    let mut entries = Vec::new();
    for field in expanded_client_fields(spec, request_ty) {
        if resolve_field_source(field, route) == source {
            entries.push(format!(
                "{}: req.{}",
                dart_string(&field_wire_name(field)),
                dart_field_name(field)
            ));
        }
    }
    if entries.is_empty() {
        "const <String, Object?>{}".to_string()
    } else {
        format!("<String, Object?>{{ {} }}", entries.join(", "))
    }
}

fn render_dart_headers(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    let mut entries = Vec::new();
    for field in expanded_client_fields(spec, request_ty) {
        if resolve_field_source(field, route) == FieldSource::Header {
            entries.push(format!(
                "{}: req.{}.toString()",
                dart_string(&field_wire_name(field)),
                dart_field_name(field)
            ));
        }
    }
    if entries.is_empty() {
        "const <String, String>{}".to_string()
    } else {
        format!("<String, String>{{ {} }}", entries.join(", "))
    }
}

fn render_java_map(
    spec: &ApiSpec,
    request_ty: &TypeDef,
    route: &RestRoute,
    source: FieldSource,
) -> String {
    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| resolve_field_source(field, route) == source)
        .map(|field| {
            format!(
                "{} , req.{}",
                java_string(&field_wire_name(field)),
                java_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "Map.of()".to_string()
    } else {
        format!("mapOf({})", entries.join(", "))
    }
}

fn render_java_headers(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| resolve_field_source(field, route) == FieldSource::Header)
        .map(|field| {
            format!(
                "{} , String.valueOf(req.{})",
                java_string(&field_wire_name(field)),
                java_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "Map.of()".to_string()
    } else {
        format!("stringMapOf({})", entries.join(", "))
    }
}

fn render_kotlin_map(
    spec: &ApiSpec,
    request_ty: &TypeDef,
    route: &RestRoute,
    source: FieldSource,
) -> String {
    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| resolve_field_source(field, route) == source)
        .map(|field| {
            format!(
                "{} to req.{}",
                kotlin_string(&field_wire_name(field)),
                kotlin_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "emptyMap()".to_string()
    } else {
        format!("mapOf({})", entries.join(", "))
    }
}

fn render_kotlin_headers(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| resolve_field_source(field, route) == FieldSource::Header)
        .map(|field| {
            format!(
                "{} to req.{}.toString()",
                kotlin_string(&field_wire_name(field)),
                kotlin_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "emptyMap()".to_string()
    } else {
        format!("mapOf({})", entries.join(", "))
    }
}

fn render_swift_dict(
    spec: &ApiSpec,
    request_ty: &TypeDef,
    route: &RestRoute,
    source: FieldSource,
) -> String {
    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| resolve_field_source(field, route) == source)
        .map(|field| {
            format!(
                "{}: req.{}",
                swift_string(&field_wire_name(field)),
                swift_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "[:]".to_string()
    } else {
        format!("[{}]", entries.join(", "))
    }
}

fn render_swift_headers(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| resolve_field_source(field, route) == FieldSource::Header)
        .map(|field| {
            format!(
                "{}: String(describing: req.{})",
                swift_string(&field_wire_name(field)),
                swift_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "[:]".to_string()
    } else {
        format!("[{}]", entries.join(", "))
    }
}

fn render_body(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    if matches!(
        route.method,
        HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
    ) {
        return "undefined".to_string();
    }

    let mut entries = Vec::new();
    for field in expanded_client_fields(spec, request_ty) {
        let source = resolve_field_source(field, route);
        if matches!(source, FieldSource::Json | FieldSource::Form) {
            entries.push(format!(
                "{}: {}",
                ts_property(field_wire_name(field)),
                req_access(field_property_name(field))
            ));
        }
    }
    if entries.is_empty() {
        "undefined".to_string()
    } else {
        format!("{{ {} }}", entries.join(", "))
    }
}

fn render_swift_body(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    if matches!(
        route.method,
        HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
    ) {
        return "nil".to_string();
    }

    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| {
            matches!(
                resolve_field_source(field, route),
                FieldSource::Json | FieldSource::Form
            )
        })
        .map(|field| {
            format!(
                "{}: req.{}",
                swift_string(&field_wire_name(field)),
                swift_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "nil".to_string()
    } else {
        format!("[{}]", entries.join(", "))
    }
}

fn render_java_body(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    if matches!(
        route.method,
        HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
    ) {
        return "null".to_string();
    }

    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| {
            matches!(
                resolve_field_source(field, route),
                FieldSource::Json | FieldSource::Form
            )
        })
        .map(|field| {
            format!(
                "{} , req.{}",
                java_string(&field_wire_name(field)),
                java_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "null".to_string()
    } else {
        format!("jsonObject({})", entries.join(", "))
    }
}

fn render_kotlin_body(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    if matches!(
        route.method,
        HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
    ) {
        return "null".to_string();
    }

    let entries = expanded_client_fields(spec, request_ty)
        .into_iter()
        .filter(|field| {
            matches!(
                resolve_field_source(field, route),
                FieldSource::Json | FieldSource::Form
            )
        })
        .map(|field| {
            format!(
                "{} to req.{}",
                kotlin_string(&field_wire_name(field)),
                kotlin_field_name(field)
            )
        })
        .collect::<Vec<_>>();
    if entries.is_empty() {
        "null".to_string()
    } else {
        format!("jsonObject({})", entries.join(", "))
    }
}

fn render_dart_body(spec: &ApiSpec, request_ty: &TypeDef, route: &RestRoute) -> String {
    if matches!(
        route.method,
        HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
    ) {
        return "null".to_string();
    }

    let mut entries = Vec::new();
    for field in expanded_client_fields(spec, request_ty) {
        let source = resolve_field_source(field, route);
        if matches!(source, FieldSource::Json | FieldSource::Form) {
            entries.push(format!(
                "{}: req.{}",
                dart_string(&field_wire_name(field)),
                dart_field_name(field)
            ));
        }
    }
    if entries.is_empty() {
        "null".to_string()
    } else {
        format!("<String, Object?>{{ {} }}", entries.join(", "))
    }
}

fn resolve_field_source(field: &Field, route: &RestRoute) -> FieldSource {
    match field.source {
        FieldSource::Auto => {
            let name = normalize_ident(&field_wire_name(field));
            if route_path_params(&route.path).contains(&name) {
                FieldSource::Path
            } else if matches!(
                route.method,
                HttpMethod::Get | HttpMethod::Head | HttpMethod::Delete
            ) {
                FieldSource::Query
            } else {
                FieldSource::Json
            }
        }
        other => other,
    }
}

fn expanded_client_fields<'a>(spec: &'a ApiSpec, ty: &'a TypeDef) -> Vec<&'a Field> {
    let mut fields = Vec::new();
    let mut stack = HashSet::new();
    expand_client_fields(spec, ty, &mut stack, &mut fields);
    fields
}

fn expand_client_fields<'a>(
    spec: &'a ApiSpec,
    ty: &'a TypeDef,
    stack: &mut HashSet<String>,
    fields: &mut Vec<&'a Field>,
) {
    if !stack.insert(ty.name.clone()) {
        return;
    }
    for field in &ty.fields {
        if field.embedded {
            if let Some(nested) = spec
                .types
                .iter()
                .find(|candidate| candidate.name == field.ty)
            {
                expand_client_fields(spec, nested, stack, fields);
                continue;
            }
        }
        fields.push(field);
    }
    stack.remove(&ty.name);
}

fn route_path_params(path: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut chars = path.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            ':' => {
                let mut name = String::new();
                while let Some(&next) = chars.peek() {
                    if next == '/' {
                        break;
                    }
                    name.push(next);
                    chars.next();
                }
                if !name.is_empty() {
                    names.push(normalize_ident(&name));
                }
            }
            '{' => {
                let mut name = String::new();
                for next in chars.by_ref() {
                    if next == '}' {
                        break;
                    }
                    name.push(next);
                }
                if !name.is_empty() {
                    names.push(normalize_ident(&name));
                }
            }
            _ => {}
        }
    }
    names
}

fn resolved_handler_name(route: &RestRoute) -> String {
    route
        .handler
        .as_ref()
        .map(|handler| to_snake_case(handler))
        .unwrap_or_else(|| rest::handler_name_for_openapi(&route.method, &route.path))
}

fn field_property_name(field: &Field) -> String {
    if matches!(field.source, FieldSource::Header) {
        return field.name.clone();
    }
    field
        .json_name
        .as_deref()
        .or(field.wire_name.as_deref())
        .unwrap_or(&field.name)
        .to_string()
}

fn field_wire_name(field: &Field) -> String {
    field
        .wire_name
        .as_deref()
        .or(field.json_name.as_deref())
        .unwrap_or(&field.name)
        .to_string()
}

fn req_access(property: String) -> String {
    if is_ts_ident(&property) {
        format!("req.{property}")
    } else {
        format!("req[{}]", ts_string(&property))
    }
}

fn ts_property(property: String) -> String {
    if is_ts_ident(&property) {
        property
    } else {
        ts_string(&property)
    }
}

fn ts_type(ty: &str) -> &'static str {
    match ty {
        "String" | "string" => "string",
        "bool" | "boolean" => "boolean",
        "int" | "uint" | "i32" | "i64" | "u32" | "u64" | "int32" | "int64" | "uint32"
        | "uint64" | "float" | "double" | "f32" | "f64" => "number",
        _ => "unknown",
    }
}

fn dart_type(ty: &str) -> &'static str {
    match ty {
        "String" | "string" => "String",
        "bool" | "boolean" => "bool",
        "int" | "uint" | "i32" | "i64" | "u32" | "u64" | "int32" | "int64" | "uint32"
        | "uint64" => "int",
        "float" | "double" | "f32" | "f64" => "double",
        _ => "dynamic",
    }
}

fn java_type(ty: &str) -> &'static str {
    match ty {
        "String" | "string" => "String",
        "bool" | "boolean" => "boolean",
        "int" | "i32" | "int32" => "int",
        "uint" | "i64" | "u32" | "u64" | "int64" | "uint32" | "uint64" => "long",
        "float" | "f32" => "float",
        "double" | "f64" => "double",
        _ => "Object",
    }
}

fn kotlin_type(ty: &str) -> &'static str {
    match ty {
        "String" | "string" => "String",
        "bool" | "boolean" => "Boolean",
        "int" | "i32" | "int32" => "Int",
        "uint" | "i64" | "u32" | "u64" | "int64" | "uint32" | "uint64" => "Long",
        "float" | "f32" => "Float",
        "double" | "f64" => "Double",
        _ => "Any?",
    }
}

fn swift_type(ty: &str) -> String {
    match ty {
        "String" | "string" => "String".to_string(),
        "bool" | "boolean" => "Bool".to_string(),
        "int" | "i32" | "int32" => "Int".to_string(),
        "uint" | "i64" | "u32" | "u64" | "int64" | "uint32" | "uint64" => "Int64".to_string(),
        "float" | "f32" => "Float".to_string(),
        "double" | "f64" => "Double".to_string(),
        other => other.to_string(),
    }
}

fn dart_from_json_expr(field: &Field) -> String {
    let key = dart_string(&field_wire_name(field));
    match dart_type(&field.ty) {
        "String" => format!("json[{key}] as String"),
        "bool" => format!("json[{key}] as bool"),
        "int" => format!("json[{key}] as int"),
        "double" => format!("(json[{key}] as num).toDouble()"),
        _ => format!("json[{key}]"),
    }
}

fn dart_field_name(field: &Field) -> String {
    let raw = field_property_name(field);
    lower_camel(&to_snake_case(&raw))
}

fn java_field_name(field: &Field) -> String {
    let raw = field_property_name(field);
    lower_camel(&to_snake_case(&raw))
}

fn kotlin_field_name(field: &Field) -> String {
    let raw = field_property_name(field);
    lower_camel(&to_snake_case(&raw))
}

fn swift_field_name(field: &Field) -> String {
    let raw = field_property_name(field);
    lower_camel(&to_snake_case(&raw))
}

fn dart_string(input: &str) -> String {
    format!("{:?}", input)
}

fn java_string(input: &str) -> String {
    format!("{:?}", input)
}

fn kotlin_string(input: &str) -> String {
    format!("{:?}", input)
}

fn swift_string(input: &str) -> String {
    format!("{:?}", input)
}

fn http_method(method: &HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "GET",
        HttpMethod::Head => "HEAD",
        HttpMethod::Post => "POST",
        HttpMethod::Put => "PUT",
        HttpMethod::Patch => "PATCH",
        HttpMethod::Delete => "DELETE",
    }
}

fn lower_camel(input: &str) -> String {
    let mut parts = input.split('_').filter(|part| !part.is_empty());
    let Some(first) = parts.next() else {
        return "call".to_string();
    };
    let mut out = first.to_string();
    for part in parts {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn normalize_ident(input: &str) -> String {
    input.replace('-', "_")
}

fn is_ts_ident(input: &str) -> bool {
    let mut chars = input.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first == '$' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn ts_string(input: &str) -> String {
    format!("{:?}", input)
}

#[cfg(test)]
mod tests {
    use crate::parser::parse_api;

    use super::*;

    #[test]
    fn renders_typed_fetch_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
                @handler ping
                head /ping (EmptyReq) returns (EmptyResp)
                @handler login
                post /login (LoginReq) returns (LoginResp)
                @handler updateUser
                patch /users/:id (UpdateUserReq) returns (UserResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
                LoginReq {
                    username string `json:"username"`
                    password string `json:"password"`
                }
                UpdateUserReq {
                    id u64 `path:"id"`
                    name string `json:"name"`
                }
                LoginResp {
                    token string `json:"token"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_ts_client(&spec);
        assert!(client.contains("export interface GetUserReq"));
        assert!(client.contains("export async function getUser"));
        assert!(client.contains("`/api/v1/users/${encodeURIComponent(String(req.id))}`"));
        assert!(client.contains("Authorization: req.token"));
        assert!(client.contains("q: req.q"));
        assert!(client.contains("export async function ping"));
        assert!(client.contains("requestJson<EmptyResp>(\"HEAD\""));
        assert!(client.contains("export async function login"));
        assert!(client.contains("username: req.username"));
        assert!(client.contains("export async function updateUser"));
        assert!(client.contains("\"PATCH\""));
        assert!(client.contains("name: req.name"));
    }

    #[test]
    fn renders_embedded_request_fields_flattened_in_clients() {
        let spec = parse_api(
            r#"
            service user-api {
                @handler createUser
                post /users (CreateUserReq) returns (UserResp)
            }
            type (
                BaseReq {
                    traceId string `json:"traceId"`
                }
                CreateUserReq {
                    BaseReq
                    name string `json:"name"`
                }
                UserResp {
                    id u64 `json:"id"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_ts_client(&spec);

        assert!(client.contains("export interface CreateUserReq"));
        assert!(client.contains("traceId: string;"));
        assert!(client.contains("name: string;"));
        assert!(client.contains("traceId: req.traceId"));
        assert!(client.contains("name: req.name"));
        assert!(!client.contains("baseReq:"));
        assert!(!client.contains("req.baseReq"));
    }

    #[test]
    fn renders_javascript_fetch_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_js_client(&spec);
        assert!(client.contains("@typedef {Object} GetUserReq"));
        assert!(client.contains("export async function getUser(req, options = {})"));
        assert!(client.contains("`/api/v1/users/${encodeURIComponent(String(req.id))}`"));
        assert!(client.contains("Authorization: req.token"));
        assert!(!client.contains(": GetUserReq"));
    }

    #[test]
    fn renders_client_for_route_without_request() {
        let spec = parse_api(
            r#"
            service health-api {
                @handler health
                get /health returns (HealthResp)
                @handler ping
                get /ping
                @handler logout
                post /logout (LogoutReq)
            }

            type LogoutReq {
                token string `json:"token"`
            }

            type HealthResp {
                ok bool `json:"ok"`
            }
            "#,
        )
        .expect("valid api");

        let client = render_ts_client(&spec);
        assert!(client.contains("export interface EmptyReq"));
        assert!(client.contains("export interface EmptyResp"));
        assert!(client.contains("export async function health(req: EmptyReq = {}"));
        assert!(client.contains("requestJson<HealthResp>(\"GET\", `/health`"));
        assert!(client.contains("export async function ping(req: EmptyReq = {}"));
        assert!(client.contains("requestJson<EmptyResp>(\"GET\", `/ping`"));
        assert!(client.contains("export async function logout(req: LogoutReq"));
        assert!(client.contains("requestJson<EmptyResp>(\"POST\", `/logout`"));

        let js = render_js_client(&spec);
        assert!(js.contains("@param {EmptyReq} [req]"));
        assert!(js.contains("export async function health(req = {}, options = {})"));

        let dart = render_dart_client(&spec);
        assert!(dart.contains("class EmptyReq"));
        assert!(dart.contains("class EmptyResp"));
        assert!(dart.contains("Future<HealthResp> health(EmptyReq req"));
        assert!(dart.contains("final uri = _uri('/health'"));
        assert!(dart.contains("Future<EmptyResp> ping(EmptyReq req"));
        assert!(dart.contains("Future<EmptyResp> logout(LogoutReq req"));
    }

    #[test]
    fn renders_dart_http_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
                @handler login
                post /login (LoginReq) returns (LoginResp)
                @handler updateUser
                patch /users/:id (UpdateUserReq) returns (UserResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
                LoginReq {
                    username string `json:"username"`
                    password string `json:"password"`
                }
                UpdateUserReq {
                    id u64 `path:"id"`
                    name string `json:"name"`
                }
                LoginResp {
                    token string `json:"token"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_dart_client(&spec);
        assert!(client.contains("import 'package:http/http.dart' as http;"));
        assert!(client.contains("class RozeApiClient"));
        assert!(client.contains("case 'HEAD':"));
        assert!(client.contains("_httpClient.head"));
        assert!(client.contains("Future<UserResp> getUser(GetUserReq req"));
        assert!(client.contains("'/api/v1/users/${Uri.encodeComponent(req.id.toString())}'"));
        assert!(client.contains("\"Authorization\": req.token.toString()"));
        assert!(client.contains("\"q\": req.q"));
        assert!(client.contains("break;"));
        assert!(client.contains("Future<LoginResp> login(LoginReq req"));
        assert!(client.contains("\"username\": req.username"));
        assert!(client.contains("Future<UserResp> updateUser(UpdateUserReq req"));
        assert!(client.contains("\"PATCH\""));
        assert!(client.contains("_httpClient.patch"));
    }

    #[test]
    fn renders_java_http_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
                @handler login
                post /login (LoginReq) returns (LoginResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
                LoginReq {
                    username string `json:"username"`
                    password string `json:"password"`
                }
                LoginResp {
                    token string `json:"token"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_java_client(&spec);
        assert!(client.contains("import java.net.http.HttpClient;"));
        assert!(client.contains("public final class RozeApiClient"));
        assert!(client.contains("public String getUser(GetUserReq req)"));
        assert!(client.contains("\"/api/v1/users/\" + urlEncode(String.valueOf(req.id))"));
        assert!(client.contains("stringMapOf(\"Authorization\" , String.valueOf(req.token))"));
        assert!(client.contains("mapOf(\"q\" , req.q)"));
        assert!(client.contains("public static final class GetUserReq"));
        assert!(client.contains("public long id;"));
        assert!(client.contains("public String login(LoginReq req)"));
        assert!(
            client.contains("jsonObject(\"username\" , req.username, \"password\" , req.password)")
        );
    }

    #[test]
    fn renders_kotlin_http_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
                @handler login
                post /login (LoginReq) returns (LoginResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
                LoginReq {
                    username string `json:"username"`
                    password string `json:"password"`
                }
                LoginResp {
                    token string `json:"token"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_kotlin_client(&spec);
        assert!(client.contains("import java.net.http.HttpClient"));
        assert!(client.contains("data class GetUserReq"));
        assert!(client.contains("val id: Long"));
        assert!(client.contains("class RozeApiClient"));
        assert!(client.contains("fun getUser(req: GetUserReq): String"));
        assert!(client.contains("\"/api/v1/users/\" + urlEncode(req.id.toString())"));
        assert!(client.contains("mapOf(\"Authorization\" to req.token.toString())"));
        assert!(client.contains("mapOf(\"q\" to req.q)"));
        assert!(client.contains("fun login(req: LoginReq): String"));
        assert!(client
            .contains("jsonObject(\"username\" to req.username, \"password\" to req.password)"));
    }

    #[test]
    fn renders_swift_urlsession_client() {
        let spec = parse_api(
            r#"
            @server (
                prefix: /api/v1
            )
            service user-api {
                @handler getUser
                get /users/:id (GetUserReq) returns (UserResp)
                @handler login
                post /login (LoginReq) returns (LoginResp)
            }
            type (
                GetUserReq {
                    id u64 `path:"id"`
                    token string `header:"Authorization"`
                    q string `query:"q"`
                }
                UserResp {
                    id u64 `json:"id"`
                    name string `json:"name"`
                }
                LoginReq {
                    username string `json:"username"`
                    password string `json:"password"`
                }
                LoginResp {
                    token string `json:"token"`
                }
            )
            "#,
        )
        .expect("valid api");

        let client = render_swift_client(&spec);
        assert!(client.contains("import Foundation"));
        assert!(client.contains("public struct GetUserReq: Codable"));
        assert!(client.contains("public var id: Int64"));
        assert!(client.contains("public final class RozeApiClient"));
        assert!(client.contains("public func getUser(_ req: GetUserReq) async throws -> String"));
        assert!(client
            .contains("\"/api/v1/users/\" + String(describing: req.id).addingPercentEncoding"));
        assert!(client.contains("\"Authorization\": String(describing: req.token)"));
        assert!(client.contains("\"q\": req.q"));
        assert!(client.contains("public func login(_ req: LoginReq) async throws -> String"));
        assert!(client.contains("\"username\": req.username"));
        assert!(client.contains("URLSession"));
    }
}
