[package]
name = "roze-gateway"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tracing.workspace = true

poem.workspace = true
roze-config = { path = "../roze-config" }
roze-jwt = { path = "../roze-jwt" }
roze-trace = { path = "../roze-trace" }
